// Demo Hub — product & video data model
//
// `youtubeId` accepts ANY of these:
//   - a bare video id ........ "M7lc1UVf-VE"
//   - a full watch URL ....... "https://www.youtube.com/watch?v=GX9x62kFsVU"
//   - a youtu.be link ........ "https://youtu.be/GX9x62kFsVU"
//   - a playlist watch URL ... "https://www.youtube.com/watch?v=ID&list=PLAYLIST_ID"
//
// UNLISTED PLAYLISTS: add a `playlistId` (the value after list= in the playlist URL).
//   - with a `youtubeId` too  -> that video opens inside the playlist
//   - with only `playlistId`  -> the whole playlist plays
// Unlisted playlists embed fine; only "Private" ones are blocked by YouTube.
// Example:  youtubeId: "GX9x62kFsVU", playlistId: "PLxxxxxxxxxxxxxxxx",
const PRODUCTS = [
  {
    id: "live",
    name: "Live",
    tagline: "Interactive cross-browser testing on real devices",
    icon: "",
    iconSvg: "icons/icon-14-live.svg",
    videos: [
      { id: "live-1", title: "BrowserStack Live - Bookmark URLs", youtubeId: "", duration: "",
        description: "Learn how to save and manage URLs for quick access during your live testing sessions.",
        docs: [], links: [] },
      { id: "live-2", title: "BrowserStack Live - Bug Reporting", youtubeId: "", duration: "",
        description: "Discover how to capture and report bugs directly to your project management tools while testing.",
        docs: [], links: [] },
      { id: "live-3", title: "BrowserStack Live - Multi Device Testing", youtubeId: "", duration: "",
        description: "Learn how to test your website simultaneously or seamlessly across multiple devices and browsers.",
        docs: [], links: [] },
      { id: "live-4", title: "BrowserStack Live - Accessibility Testing on Desktop Browsers", youtubeId: "", duration: "",
        description: "Understand how to evaluate your website's accessibility features on various desktop browsers.",
        docs: [], links: [] },
      { id: "live-5", title: "BrowserStack Live - Accessibility Testing on Mobile Browsers", youtubeId: "", duration: "",
        description: "Learn the steps to perform comprehensive accessibility checks on mobile browsers.",
        docs: [], links: [] },
      { id: "live-6", title: "BrowserStack Live - Download Files and Images from Real Devices", youtubeId: "", duration: "",
        description: "See how to download and verify files or images directly from remote real devices.",
        docs: [], links: [] },
      { id: "live-7", title: "BrowserStack Live - File Download", youtubeId: "", duration: "",
        description: "Learn how to test and validate file download functionalities on different browsers and devices.",
        docs: [], links: [] },
      { id: "live-8", title: "BrowserStack Live - Image Injection", youtubeId: "", duration: "",
        description: "Discover how to inject images into device cameras to test upload workflows or scanning features.",
        docs: [], links: [] },
      { id: "live-9", title: "BrowserStack Live - Network Monitoring", youtubeId: "", duration: "",
        description: "Understand how to monitor network traffic and analyze requests during your testing sessions.",
        docs: [], links: [] },
      { id: "live-10", title: "BrowserStack Live - Network Throttling", youtubeId: "", duration: "",
        description: "Learn how to simulate different network speeds, like 3G or offline modes, to test app performance.",
        docs: [], links: [] },
      { id: "live-11", title: "BrowserStack Live - QR Code and Barcode Scanning", youtubeId: "", duration: "",
        description: "See how to test QR code and barcode scanning features using real device cameras.",
        docs: [], links: [] },
      { id: "live-12", title: "BrowserStack Live - Record a Session", youtubeId: "", duration: "",
        description: "Learn how to record your interactive testing sessions for easier debugging and team sharing.",
        docs: [], links: [] },
      { id: "live-13", title: "BrowserStack Live - SIM for OTP/Message Testing", youtubeId: "", duration: "",
        description: "Discover how to use real SIM cards to test SMS and OTP workflows on remote devices.",
        docs: [], links: [] },
      { id: "live-14", title: "BrowserStack Live - Testing Apple Pay Workflows on iOS Devices", youtubeId: "", duration: "",
        description: "Understand how to validate Apple Pay integrations and payment workflows on real iOS devices.",
        docs: [], links: [] },
      { id: "live-15", title: "BrowserStack Live - Testing Audio Input", youtubeId: "", duration: "",
        description: "Learn how to test voice search, voice notes, and other audio input functionalities.",
        docs: [], links: [] },
      { id: "live-16", title: "BrowserStack Live - Testing Google Pay Workflows on Android-Chrome Devices", youtubeId: "", duration: "",
        description: "See how to test Google Pay integrations and payment flows on real Android devices using Chrome.",
        docs: [], links: [] },
      { id: "live-17", title: "BrowserStack Live - Test Internal Networks", youtubeId: "", duration: "",
        description: "Discover how to securely test local, staging, and internal websites using BrowserStack Local.",
        docs: [], links: [] },
      { id: "live-18", title: "BrowserStack Live - Timezone Specific Testing", youtubeId: "", duration: "",
        description: "Learn how to simulate different geographical timezones to test localized date and time features.",
        docs: [], links: [] },
      { id: "live-19", title: "BrowserStack Live - Upload Files", youtubeId: "", duration: "",
        description: "Understand how to test file upload functionalities from a remote device's local storage.",
        docs: [], links: [] },
      { id: "live-20", title: "BrowserStack Live - Test Across Resolutions", youtubeId: "", duration: "",
        description: "See how to verify your website's responsiveness by testing across various screen resolutions.",
        docs: [], links: [] },
      ],
  },
  {
    id: "app-live",
    name: "App Live",
    tagline: "Interactive application testing on real devices",
    icon: "",
    iconSvg: "icons/icon-10.svg",
    videos: [
      { id: "applive-1", title: "Getting Started with BrowserStack App Live", youtubeId: "", duration: "",
        description: "Learn how to start an interactive browser testing session on real browsers and devices using BrowserStack Live.",
        docs: [], links: [] },
    ],
  },
  {
    id: "automate",
    name: "Automate",
    tagline: "Browser test automation infrastructure",
    icon: "",
    iconSvg: "icons/icon-13.svg",
    videos: [
      { id: "automate-1", title: "Getting Started with BrowserStack Automate", youtubeId: "", duration: "",
        description: "Learn how to start an interactive browser testing session on real browsers and devices using BrowserStack Live.",
        docs: [], links: [] },
    ],
  },
  {
    id: "app-automate",
    name: "App Automate",
    tagline: "Automated mobile app testing on real devices",
    icon: "",
    iconSvg: "icons/icon-09.svg",
    videos: [
      { id: "app-automate-1", title: "Getting Started with BrowserStack App Automate", youtubeId: "", duration: "",
        description: "Learn how to start an interactive browser testing session on real browsers and devices using BrowserStack Live.",
        docs: [], links: [] },
    ],
  },
  {
    id: "test-management",
    name: "Test Management",
    tagline: "Next-gen Test Management with AI",
    icon: "",
    iconSvg: "icons/icon-11.svg",
    videos: [
      { id: "test-management-1", title: "Getting Started with BrowserStack Test Management", youtubeId: "", duration: "",
        description: "Learn how to start an interactive browser testing session on real browsers and devices using BrowserStack Live.",
        docs: [], links: [] },
    ],
  },
  {
    id: "accessibility",
    name: "Accessibility Testing",
    tagline: "Test WCAG and ADA Compliance",
    icon: "",
    iconSvg: "icons/icon-06.svg",
    videos: [
      { id: "accessibility-1", title: "Getting Started with BrowserStack Accessibility Testing", youtubeId: "", duration: "",
        description: "Learn how to start an interactive browser testing session on real browsers and devices using BrowserStack Live.",
        docs: [], links: [] },
    ],
  },
  {
    id: "Low-Code-Automation",
    name: "Low Code Automation",
    tagline: "Feature demos for Low Code Automation",
    icon: "",
    iconSvg: "icons/icon-04-lca.svg",
    videos: [
      { id: "lc-1", title: "1.1 Get Started | Record Your First Test on Low Code Automation", youtubeId: "https://www.youtube.com/watch?v=x0bHlVV2psU&list=PLN1KfW8k2lAk", duration: "05:11",
        description: "Start your Low Code Automation journey by recording a test directly in your browser. The intuitive test recorder turns every click, input, and navigation into an automated step in real time, with no coding or infrastructure setup, so QA testers, developers, and citizen testers can build their first automated test in minutes.",
        docs: [{ label: "Create Your First Test", url: "https://www.browserstack.com/docs/low-code-automation/get-started/create-test" }], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-2", title: "1.2 Get Started | Add Validations: Visual, Text Assert, Element Presence", youtubeId: "https://youtu.be/_3k8DXgi8Cs?si=jWaECArBEYmwKCyq", duration: "03:31",
        description: "Add detailed validations to your recorded steps to verify both functionality and visuals. Assert on text, elements, and page state so every critical checkpoint in your end-to-end journey is checked automatically on each run.",
        docs: [{ label: "Adding Validations", url: "https://www.browserstack.com/docs/low-code-automation/test-recording/validations" }], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-3", title: "1.3 Get Started | Create Test Suites & Run Cross-Browser Builds", youtubeId: "https://www.youtube.com/watch?v=8ttgxw3dpX4&list=PLN1KfW8k2lAk", duration: "02:08",
        description: "Create your test suite and replay recorded tests on real desktop and mobile browsers in the BrowserStack cloud. Run the same flow across multiple browser and OS combinations to confirm consistent behaviour everywhere, while intelligent wait timeouts automatically reduce flakiness with zero infrastructure to manage.",
        docs: [{ label: "Perform Cross Browser Testing", url: "https://www.browserstack.com/docs/low-code-automation/type-of-testing/cross-browser-testing" }], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-4", title: "1.4 Get Started | Debug Tests with Video, Screenshots & Logs", youtubeId: "https://www.youtube.com/watch?v=tVD4XdkpjSI&list=PLN1KfW8k2lAk&index=4", duration: "04:30",
        description: "Diagnose failures fast using rich debugging data. Step through each action with screenshots, video, and logs from the run to understand exactly what happened, and monitor the ongoing health of your tests.",
        docs: [{label:"Test Reporting and Debugging", url:"https://www.browserstack.com/docs/low-code-automation/test-debugging/overview"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-5", title: "1.5 Get Started | Test Internal & Staging Environments with BrowserStack Local", youtubeId: "https://www.youtube.com/watch?v=BDrDstNDnv0&list=PLN1KfW8k2lAk", duration: "03:55",
        description: "Test applications that aren't publicly accessible. Use BrowserStack Local to securely run low-code tests against internal, staging, UAT, and pre-production environments hosted behind your firewall or proxy.",
        docs: [{label: "Test on Internal Networks", url: "https://www.browserstack.com/docs/low-code-automation/local-testing"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-6", title: "1.6 Get Started | Run Tests in Your CI/CD Pipeline", youtubeId: "https://www.youtube.com/watch?v=8vXaAJlpV40&list=PLN1KfW8k2lAk", duration: "02:43",
        description: "Shift your low-code tests left by running them automatically in your pipeline. Trigger tests on every build or deployment and pull results back into your CI/CD workflow for continuous, fast feedback.",
        docs: [{label: "Integrate with CI/CD Pipelines", url: "https://www.browserstack.com/docs/low-code-automation/cicd-integrations/rest-api"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-7", title: "2.1 Test faster and broaden Coverage | AI-Powered Testing", youtubeId: "https://www.youtube.com/watch?v=CGXw64t2Nrk&list=PLN1KfW8k2lAk", duration: "05:42",
        description: "Use AI to turn plain natural-language instructions into ready-to-run test steps. Generate test cases and steps from a simple prompt to accelerate authoring, then fine-tune them in the recorder, lowering the learning curve even further.",
        docs: [{label: "AI Powered Testing", url: "https://www.browserstack.com/docs/low-code-automation/test-recording/browserstack-ai"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-8", title: "2.2 Test faster and broaden Coverage | IP Geolocation Testing", youtubeId: "https://www.youtube.com/watch?v=spToUIJN6lY&list=PLN1KfW8k2lAk", duration: "03:21",
        description: "Verify region-specific behaviour by running tests from different geographic locations. Check localised content, pricing, language, and geo-gated features using IP-based geolocation to ensure a consistent experience for global users.",
        docs: [{label: "IP Geolocation", url: "https://www.browserstack.com/docs/low-code-automation/test-real-user-conditions/ip-geo-location"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-9", title: "3.1 Reliable & Reusable Tests | Override Element Locators", youtubeId: "https://www.youtube.com/watch?v=HnkE_HGklK4&list=PLN1KfW8k2lAk", duration: "02:04",
        description: "Improve reliability by customising how your tests identify elements. Override auto-generated locators with your own selectors to pinpoint hard-to-identify or dynamic elements, working alongside AI self-heal to keep tests passing as your application changes.",
        docs: [{label: "Configure Test Steps", url: "https://www.browserstack.com/docs/low-code-automation/test-recording/configure-step-behaviour"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-10", title: "3.2 Reliable & Reusable Tests | Reuse Steps with Modules", youtubeId: "https://www.youtube.com/watch?v=3ncZwuooNZc&list=PLN1KfW8k2lAk", duration: "03:07",
        description: "Keep large test suites maintainable by grouping repeated steps, such as login or checkout, into reusable modules. Update a flow once and have the change reflected across every test that uses it, cutting duplication and ongoing maintenance.",
        docs: [{label: "Create Modules", url: "https://www.browserstack.com/docs/low-code-automation/best-practices/modules"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-11", title: "3.3 Reliable & Reusable Tests | Data-Driven Testing with Variables, Secrets & Datasets", youtubeId: "https://www.youtube.com/watch?v=-g-5h5r5_PY&list=PLN1KfW8k2lAk", duration: "03:27",
        description: "Run the same test across many data combinations using built-in Variables, Secrets, and test datasets. Parameterise inputs, securely store credentials as masked secrets, and validate your application against multiple data sets without rebuilding the test.",
        docs: [{label: "Add Variables, Secrets and Datasets", url: "https://www.browserstack.com/docs/low-code-automation/best-practices/data-driven-testing"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-12", title: "3.4 Reliable & Reusable Tests | Add Conditional Flows", youtubeId: "https://www.youtube.com/watch?v=uAJO7DYCkpo&list=PLN1KfW8k2lAk", duration: "02:50",
        description: "Make your tests handle real-world unpredictability by adding conditional logic. Branch a test based on what actually appears on screen, such as pop-ups, A/B variations, or dynamic states, so a single test adapts to multiple scenarios instead of breaking.",
        docs: [{label: "Conditional If-Else Workflows", url: "https://www.browserstack.com/docs/low-code-automation/test-recording/conditional-flow"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-13", title: "3.5 Reliable & Reusable Tests | Advanced Usecases with Custom Actions & JavaScript", youtubeId: "https://www.youtube.com/watch?v=NYob4w8V6Js&list=PLN1KfW8k2lAk", duration: "03:51",
        description: "Go beyond standard steps by adding custom actions and JavaScript snippets. Automate advanced or app-specific use cases such as custom waits, computed values, and DOM interactions, while keeping the rest of your test fully codeless.",
        docs: [{label: "Custom Actions with Javascript", url: "https://www.browserstack.com/docs/low-code-automation/test-recording/custom-actions"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-14", title: "4.1 Cover E2E Workflows | File Upload & Download Scenarios", youtubeId: "https://www.youtube.com/watch?v=tMB83Ag1-U8&list=PLN1KfW8k2lAk", duration: "01:47",
        description: "Test workflows that depend on files end to end. Validate uploading documents and images into your app, and downloading files such as invoices or reports, all as part of a single low-code test.",
        docs: [{label: "File Validation", url: "https://www.browserstack.com/docs/low-code-automation/test-recording/validate-file-download"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-15", title: "4.2 Cover E2E Workflows | API Validations", youtubeId: "https://www.youtube.com/watch?v=nBwgenp1_Oo&list=PLN1KfW8k2lAk", duration: "03:02",
        description: "Combine UI and API checks in one test. Add API validation steps to verify backend responses, status codes, and payloads alongside your front-end flow for fuller end-to-end coverage from a single low-code test.",
        docs: [{label: "API Validations", url: "https://www.browserstack.com/docs/low-code-automation/test-recording/configure-api"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-16", title: "4.3 Cover E2E Workflows | Email Verification Usecases", youtubeId: "https://www.youtube.com/watch?v=rUfJQTVhIoo&list=PLN1KfW8k2lAk", duration: "03:08",
        description: "Validate email-dependent journeys without leaving your test. Cover sign-up confirmations, OTPs, password resets, and notification emails as an integrated part of your end-to-end flow.",
        docs: [{label: "Test Email Workflows", url: "https://www.browserstack.com/docs/low-code-automation/test-recording/test-email-workflows"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-17", title: "5.1 Manage & Scale | Test Version History", youtubeId: "https://www.youtube.com/watch?v=lzLjxx6lEwA&list=PLN1KfW8k2lAk", duration: "03:08",
        description: "Track how a test evolves over time. Review its full version history, compare changes between revisions, and roll back to an earlier version when needed, giving teams confidence to collaborate and iterate safely..",
        docs: [{label: "Test Version History", url: "https://www.browserstack.com/docs/low-code-automation/managing-tests/test-versioning"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
      { id: "lc-18", title: "5.2 Manage & Scale | Export Low Code Tests as Automation Scripts", youtubeId: "https://www.youtube.com/watch?v=db-999ku-BY&list=PLN1KfW8k2lAk", duration: "01:32",
        description: "Bridge low-code and full-code automation. Export your recorded tests as automation scripts to give engineering a head start, reuse logic inside existing frameworks, or gradually transition critical flows into code.",
        docs: [{label: "Export Test Cases using API", url: "https://www.browserstack.com/docs/low-code-automation/advanced-use-cases/export-tests"}], links: [{label: "Contact BrowserStack Support", url: "https://www.browserstack.com/contact?ref=helpdesk-bottom-contact-us-cta"}] },
    ],
  },
  
  {
    id: "analytics",
    name: "Analytics Suite",
    tagline: "Insights that drive decisions",
    icon: "📊",
    videos: [
      {
        id: "an-1",
        title: "Getting Started with Analytics Suite",
        youtubeId: "",
        description:
          "A quick tour of the Analytics Suite dashboard, key metrics, and how to build your first report.",
        docs: [
          { label: "Quickstart Guide", url: "https://example.com/analytics/quickstart" },
          { label: "API Reference", url: "https://example.com/analytics/api" },
        ],
        links: [
          { label: "Community Forum", url: "https://example.com/community" },
          { label: "Release Notes", url: "https://example.com/analytics/releases" },
        ],
      },
      {
        id: "an-2",
        title: "Building Custom Dashboards",
        youtubeId: "",
        description:
          "Learn how to create, customize, and share dashboards tailored to your team's needs.",
        docs: [{ label: "Dashboard Docs", url: "https://example.com/analytics/dashboards" }],
        links: [{ label: "Template Gallery", url: "https://example.com/templates" }],
      },
    ],
  },
  
  {
    id: "automation",
    name: "Automation Engine",
    tagline: "Work that runs itself",
    icon: "⚡",
    videos: [
      {
        id: "au-1",
        title: "Creating Your First Workflow",
        youtubeId: "",
        description:
          "Automate repetitive tasks with triggers, conditions, and actions — no code required.",
        docs: [{ label: "Workflow Docs", url: "https://example.com/automation/workflows" }],
        links: [{ label: "Recipe Library", url: "https://example.com/automation/recipes" }],
      },
    ],
  },
];